### PR TITLE
LPS-60134

### PR DESCRIPTION
**Pull request by BryanEngler**
Hi daniel, I think this might address the issue of re-prioritizing every layout. With this fix, we now only update priorities on layouts where we do know the priority, and on layouts that were deleted. For deleted layouts, they still get moved to the bottom of the list, but this would also occur in a publish of all pages with the current functionality. Let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:retest

**Comment by BryanEngler** [comment]
just added a SF commit

**Comment by danielkocsis** [comment]
Hey @BryanEngler,

sorry for the late response I was in a conference last week. So the algorithm looks a bit complex now, and I am note sure I am aware every part of it, but my question is how does this logic prevents duplication? Now we do not refresh all the priorities, so how can we prevent that a non-refreshed layout has the same as a refreshed one, and how we merge these 2 sets: the refreshed layouts with the non-refreshed ones?

**Comment by BryanEngler** [comment]
i dont know if i fully understand your question, but i assume when you say duplication you are referring to duplicate priorities within a group of sibling layouts.

basically what we are doing is taking each group of sibling layouts and looking at them as their own "unit".

for each "unit" of siblings, we either update ALL of the priorities or NONE of the priorities. in my comment above when i said we update priorities on the layouts where we "know" the priority, well the way we "know" the priority is when all of the layouts in each unit of siblings are selected for publish.

so it is still kind of an "all or nothing" approach like before, but now its within the "scope" of sibling layouts. so there shouldnt be a need to ever merge a set of updated layouts with non-updated layouts.

the only conflict we have to deal with is when there are deleted pages, and we do that by increasing their priority until its not equal to any of the known priorities. this is also similar to the previous behavior.

i hope that helps, if you have other questions let me know. or if i didnt understand, maybe give me an example of steps that would illustrate the situation you are talking about. thanks!

**Comment by danielkocsis** [comment]
I meant the duplication within the layout set, so when we update a set of layouts (group of siblings), how we prevent that the updated values conflict with other values that are not updated because they are not in this sibling group? Like child, parent layout or elements of a different sub-tree? So my fear is that this method won't prevent duplication within the whole layout set,  prevents only duplication within a set of sibling layouts.

**Comment by danielkocsis** [comment]
We just had a discussion about it within the team, and we agreed that we do not want to change this before the release because the solution is complex and there is a really high risk that it won't work or some issues might appear or someone won't like it this way.. So we do not want to have this tweak right now, maybe after a longer evaluation after the release we can commit the solution, but in this phase of the release process we do not want to risk it. Could you please close this bug ticket for now? We will handle this as a feature request with this ticket: LPS-53882 If a customer still requires this change, please give them a hotfix if the are agree to do it in their own risk.

thanks,
Daniel

**Comment by BryanEngler** [comment]
ok. i thought any two layouts could have the same priority as long as they were a child/parent or in a separate sub-tree. but youre saying those priorities are not independent of each other?

i understand that you guys probably have a lot to do before the release and you dont necessarily have time to test a change in behavior like this, but i just want to make sure thats more of the reason that youre closing it, instead of me having some misunderstanding of how the priorities work.

it sounds like you are saying it could work, or at least you didnt really say why it wont work, but that you cant test it enough before the release to be really confident. is that correct?

**Comment by danielkocsis** [comment]
Yes, so it is not about you are incompetent or something, it is just about the we would like to ship it properly and we feel the risk is too high now to make a change like this without having enough time to think it trough once again and test it properly of course.

**Comment by BryanEngler** [comment]
sounds good, thanks for the explanation daniel

**Pull request closed without merging**
