### PR TITLE
LPS-93300

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-93300

### CODE REVIEW

**Comment by giros** [comment]
ci:test:sf

**Comment by giros** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72928. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/b86c04bf5a9a~1...b86c04bf5a9a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
