### PR TITLE
[TECHNICAL-SUPPORT] LPS-72927

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Hey @jonathanmccann, @mbowerman,

The fix itself looks good, however I have a concern or question to you. So in the BaseStagedModelDataHandler there is a method called fetchMissingReference, this is responsible for trying to find the referenced, but did not export models, like the ones from the parent site, or any other site. It has a fallback logic, like try to find within the import group, if it is not there try to find in the site hierarchy from bottom to top and if it still hasn't found try to find in the whole company based on the uuid. So it seems this logic doesn't work or at least not always. Could you guys check for me why it can't find the referenced model in this scenario? Because I guess the proper fix would be to fix this logic and not introduce a brand new one, or if the old one seems to be useless, then we should change it to have only one solution for the same issue.

thank you,
Daniel

**Comment by mbowerman** [comment]
Hey @danielkocsis,

From what I can see, fetchMissingReference should successfully find the content from a parent group if it gets called. The problem is, not every StagedModelDataHandler calls fetchMissingReference from its validateMissingReferences method. The BaseStagedModelDataHandler does, but some StagedModelDataHandlers, such as JournalArticleStagedModelDataHandler, do not call fetchMissingReference because they prefer to rely on their own logic that requires more than just the uuid and groupId. Therefore, I think we should continue to use this fix, rather than force all StagedModelDataHandlers to call fetchMissingReference when some may not want to call it.

**Comment by mbowerman** [comment]
ci:reopen

**Comment by danielkocsis** [comment]
Sorry guys, I wrote a long comment yesterday regarding the fix, but somehow I did not send it :( 

So, to make long story short, I can agree that we could use this proposal as well, but I have a few problems with it:

1, The fix assumes the site hierarchy on the import site is the same as on the export site (same length, same order)
2, Neither staging, nor export-import guarantees anything regarding the environment of the current site, so we can't really say if A site has a paren called B on the export site, B' will be the parent of A' on the target server
3, we proposed our fallback logic back in the day because of this unknown nature of the environment

So if we would like to go with this solution then we need a more robust logic the find the counterparts of the sites based on the tree path on the target server. We should handle when the tree-path is not equally "high" on the 2 sites. We should handle when the dependency was imported to Site B' meanwhile originally it was in site C. Since the findMissin... logic handles this like in case of   bookmarks, we have to guarantee the same complexity can be handled for journal or Dl as well. That is why originally I preferred to use one single solution because as a framework export-import should provide a consistent logic to find missing references during the import.

**Comment by mbowerman** [comment]
Hi @danielkocsis,

Although I disagree with your claim that this fix assumes the site hierarchy on the import site is the same length as that of the export site, I understand where you're coming from. We should be consistent with how we resolve missing references for each StagedModel type. I'll go ahead and modify my fix so that we use the same logic to find missing JournalArticles that we use for other StagedModel types

**Comment by danielkocsis** [comment]
Hey @mbowerman,

this commit (https://github.com/danielkocsis/liferay-portal/pull/649/commits/36a5182b848e3213bf8cabfd4e807b12fba905de) drove me when I examined your solution. From this it seems to me you have the original and the import site treePath, and you split those which results in 2 arrays. Than you iterate through (in one single loop) those arrays and make pairs by their position until one of the arrays ends. So regarding the length, yes, literally this you are not assuming the same length, it ends when the shortest ends. But regarding the matching part, this solution is simply assuming that the 1st is the same as the other 1st, etc... And my problem is that we don't have any logic that forces this rule. So that is why I suggested a more flexible rule to find the elements. but as you said, the have one generic consistent solution idea is stronger then my thoughts regarding this solution.

thanks for doing the change!
Daniel

**Comment by mbowerman** [comment]
Hi @danielkocsis,

Please see the following three pull requests:

https://github.com/danielkocsis/liferay-portal/pull/653
https://github.com/danielkocsis/com-liferay-journal/pull/2
https://github.com/danielkocsis/com-liferay-dynamic-data-mapping/pull/1

**Pull request closed without merging**
