### PR TITLE
[TS] | LPS-94704

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
cc / @ricardocousolr

**Comment by danielkocsis** [comment]
ci:test:staging

**Comment by danielkocsis** [comment]
ci:test:sf

**Comment by danielkocsis** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Hey @crodriguezy,

is this issue only affect export/import? Or staging publication in case of individual portlets as well?

thanks,
Daniel

**Comment by crodriguezy** [comment]
Hi @danielkocsis ,

We have only been testing the export/import porlet since the error described in https://issues.liferay.com/browse/LPS-94704 is related to it. We have also confirmed that it does not break the functionality fixed by the https://issues.liferay.com/browse/LPS-64405, which is causing this regression.

Now you mentioned it we just checked that it also works correctly for local staging + export/import scenarios. We suppose the ci tests would detect those kind of errors that our change may cause: the ones detected [here](https://github.com/danielkocsis/liferay-portal/pull/730#issuecomment-490938209) are not related to them (the don't find the search element in the sites panel), so I guess we'll need to see what happens after these tests are fixed.

Anyway, have you detected any error related during your review?

cc/ @ricardocousolr

**Comment by crodriguezy** [comment]
ci:test:staging

**Comment by danielkocsis** [comment]
Hey @crodriguezy,

the fix looks goof, however I wanted to be sure you manually tested and also considered every scenario because I am not sure about the test coverage regarding all those.

I'll move forward the changes to Brian.

thanks,
Daniel

**Comment by crodriguezy** [comment]
Ok @danielkocsis, 

Maybe it would be preferable to wait until QA fixes the tests (there is a common failure) before sending it to Brian, so all the staging tests are able to be executed here. Just to make sure the PR does not break the standard ones, since we did some manual tests but we are not sure if they were enough.

Thank you.

**Comment by crodriguezy** [comment]
It seems the common error (search element not found) is not happening any more, and none of the rest of the staging tests have found errors related to this PR.

**Comment by crodriguezy** [comment]
ci:test:staging

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73008. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
