### PR TITLE
[TECHNICAL-SUPPORT] LPS-69227

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Hey @jonathanmccann,

I was in the DevCon last week, so I need some time to clean up my backlog, but I'll try to check it ASAP.

thanks,
Daniel

**Comment by danielkocsis** [comment]
Hey @jonathanmccann,


so we had a discussion with Julio about the solution and we agree on that we need a more generic one, because these one time solution that tries to patch around the problem are not the ones we would need for longer time. So we propose to create a model listener to the company object that reacts when the default local is being changed and this particular listener is for Groups only, so it would change the localized attributes of the existing group entities (like nameMap, descriptionMap, etc...) like this:

If it doesn't have a value associated with the new default locale, it copies the value of the old default locale to the new one, otherwise continue.

Could you guys please change the fix accordingly?

thanks,
Daniel

**Comment by jonathanmccann** [comment]
@cleydyr

**Comment by cleydyr** [comment]
Thanks for the observations, @danielkocsis and for the heads-up, @jonathanmccann. I'll change the fix according to the recommended specification.

**Pull request closed without merging**
