### PR TITLE
LPS-96123 null check added before applying lambdas

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:change-tracking

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74019. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/bf7a037e0996~1...bf7a037e0996) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
