### PR TITLE
LPS-94854

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/73693

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73778. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/dfb85d0d9315~2...dfb85d0d9315) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73829. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/10a3bd9ecd72~3...10a3bd9ecd72) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73836. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/752030ed94fa~3...752030ed94fa) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73892. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/d93272359aea~3...d93272359aea) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73895. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/f8a1ec0ac252~2...f8a1ec0ac252) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73938. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/6f1eb0e667de~2...6f1eb0e667de) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74061. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/6108c388c9c0~4...6108c388c9c0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74069. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/5bf66f8d66ec~5...5bf66f8d66ec) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
