### PR TITLE
LPS-92517 buildLang

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2368. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/76e33961d8ec~1...76e33961d8ec) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
