### PR TITLE
LPS-52868

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Hi @danielkocsis  @matethurzo

**LPS-52868** pull request for 6.2.x was stopped by Zoltan because it wasn't commited to master, see:
  - https://github.com/zoltantakacs/liferay-portal-ee/pull/642#issuecomment-95464218

After some tests, this issue is reproduced at master, so I have "forwardported" the original commits of that pull request to master.

I want to add this LPS-52868 to 6.2 fixpack and this is not possible until is commited at master

Please review this pull, the commits for master are similar except changes of **export_actionable_dynamic_query.ftl** that must be done at **service_base_impl.ftl** for this branch.

Thank you

### CODE REVIEW

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Hey @jorgediaz-lr,


could you please make sure that the following situations work well after applying the fix:

1. When we modify a draft on stage (make it approved)  and make it publishable we can publish it, and on live the same item is modified, not a new one is created

2, when we delete a draft on stage we can publish the deletion event to live to delete the same draft

Otherwise the fix looks good, so if these cases are working it is good to go.

thanks,
Daniel

**Comment by jorgediaz-lr** [comment]
Hi @danielkocsis,

I have tested this case at master and works fine.

You can merge it to master.

Thank you

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26873. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
