### PR TITLE
LPS-89175 exception handling fix

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72976. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
