### PR TITLE
LPS-84497 Activate/Deactivate added to LayoutSetPrototype list options

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76210. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/b7fd0d94d963~2...b7fd0d94d963) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
