### PR TITLE
LPS-92534 change tracking indicator redirects to the correct url

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:change-tracking

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73113. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/f3b1fa499b19~1...f3b1fa499b19) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
