### PR TITLE
LPS-97278,LPS-97533,LPS-97537 Change Tracking

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:test:sf

**Comment by danielkocsis** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
Hi @vicnate5,

this is the rebased version of Preston's PR. Please let me know if you are fine with the test results so I can send it to Brian.

thanks,
Daniel

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@danielkocsis Results look good :)

**Pull request closed without merging**
