### PR TITLE
LPS-71131 Fix test problems

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
Hey @pyoo47 and michaelhashimoto ,

this seems related to my issue but it is really weird that only appears when testing with HSAL have you guys seen issues like this before? Could you please help me to find the solution?

thanks,
Daniel

**Comment by pyoo47** [comment]
Daniel, sorry but neither Hashi nor I was able to find anything that we thought might help you debug this issue. I also reached out to Albert Lee to take a look but I haven't heard back yet.

Peter

**Comment by danielkocsis** [comment]
ci:retest

**Comment by akosthurzo** [comment]
Hey @pyoo47, @michaelhashimoto and @alee8888,

Were you able to figure out what could the be issue here? The test works fine locally.

Thanks,
Akos

**Comment by danielkocsis** [comment]
ci:retest

**Pull request closed without merging**
