### PR TITLE
[TECHNICAL-SUPPORT] LPS-71906

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/danielkocsis/liferay-portal/pull/628. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Hey @mbowerman,

for me locally the test always fails with: java.lang.AssertionError: Validator failed to flag [[/de/group/bkzhx4eu/bkzhx4eu|Link]] as invalid

Could you please check it?

And also my question is the in the past we had a loop and it seems to me this loop iterates only when the URL contains multiple group friendly url's (i am not sure whether it is valid or not). After the fix, we do not have this loop logic.

Is that correct?

**Comment by mbowerman** [comment]
Hi @danielkocsis,

> for me locally the test always fails with: java.lang.AssertionError: Validator failed to flag [[/de/group/bkzhx4eu/bkzhx4eu|Link]] as invalid

Are you sure you deployed my changes? That particular test case should fail before the fix is applied, but should pass after the fix is applied.

After checking out `jonathanmccann:pull-request-1289-LPS-71906`, running `ant all`, and then starting up a portal instance and running `gradlew testIntegration --tests *.DefaultExportImportContentProcessorTest` from the export-import-test directory, I was able to see that all tests passed with no errors. (As a side note, for some reason I also had to run `gradlew deploy` on the export-import-resources-importer module after running `ant all`; I'm not sure why this is.)

> And also my question is the in the past we had a loop and it seems to me this loop iterates only when the URL contains multiple group friendly url's (i am not sure whether it is valid or not). After the fix, we do not have this loop logic.

The whole purpose of this fix was to get rid of that loop, so that URLs that contained multiple group friendly URLs would be flagged as invalid. Why would you ever have a URL that consists of more than one group friendly URL?

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48554. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
