### PR TITLE
[TECHNICAL-SUPPORT] LPS-97544 Default classPK refers to the wrong JournalArticle

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @danielkocsis ,

Sending the new version of changes in https://github.com/brianchandotcom/liferay-portal/pull/75700

To make the solution more generic, I used `Object` as parameter and return value, since in many cases the types of keys and values don't match, e.g.: `Map<Long, Layout>` or `Map<String, Long>`.

Please review.

Thanks,
Vendel

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/danielkocsis/liferay-portal/pull/853. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/b1d6b96df15d~1...b1d6b96df15d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
