### PR TITLE
[TECH SUPPORT] LPS-71097

### PR DESCRIPTION
**Pull request by giros**
Hi @danielkocsis,

I refactored the code according to what we discussed. Please review. See https://issues.liferay.com/browse/LPS-71097 for details.

Regards,
G

### CODE REVIEW

**Comment by giros** [comment]
ci:retest

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49003. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/fd84ea1c8058~1...fd84ea1c8058) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49006. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/3523a9b07d23~1...3523a9b07d23) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
