### PR TITLE
[TECHNICAL-SUPPORT] LPS-72834

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/kmaria/liferay-portal/pull/29. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Hey @jonathanmccann, @JoshuaStClair,

I sent the pull to @kmaria because the change, mostly because of the number of refactors needs to be properly tested before we publish it to master. She started to work on the validation, so please give use some time and we'll get back to you with the result!

thanks,
Daniel

**Comment by danielkocsis** [comment]
Hey @jonathanmccann, @JoshuaStClair,

@kmaria found an error when using with this fix, and she logged the exception here: https://gist.github.com/kmaria/31a2958161916608c775f0151108c772

To reproduce it: 

1, Turn on staging with page variation
2, add a new site variation
3, add a new page to the newly added variation

After step #3 the staging bar becomes unavailable and the linked exception appears in the log. 

Please check this error and resend the pull when you fixed it!

thanks,
Daniel

**Comment by JoshuaStClair** [comment]
Hi @danielkocsis and @kmaria, thanks for testing the fix. I tried your steps to reproduce and even messed around for a while with combinations of Site Pages Variations, Page Variations, and adding public and private pages and I was not able to duplicate the issue you mentioned. Can you check if there might be any other steps or dependencies? I attempted this with the admin user test, and a newly created user test1 who is a site administrator.

**Comment by kmaria** [comment]
Hi @JoshuaStClair , would you try the following steps?

1. Create a new site
2. Navigate to Publishing > Staging
2. Enable local staging w/ enabling variation on public pages
3. Refresh the page
4. At Public Pages select Add Public Page 
5. Give it a name and click on Save
As a result you'll see a success message - the page is created, and at the very same time the staging bar becomes unavailable. NPE is thrown.

Another way to reproduce it:
1. Create a new site
2. Add a new Public Page
3. Navigate to Publishing > Staging
4. Enable local staging w/ enabling variation on public pages
5. Refresh the page
6. Navigate to the site
7. Add new Site Page Variation
4. At Public Pages select Add Public Page 
5. Give it a name and click on Save

Pls let me know how it goes.

**Comment by danielkocsis** [comment]
I also tried it with the steps described by @kmaria and I also got the error. Probably page versioning is the key here

**Comment by JoshuaStClair** [comment]
Thanks for the detailed instructions! I was able to reproduce that error so I will work on an appropriate fix and send it back up. The key was doing _local staging_ and not remote staging. Those steps don't cause any issues for remote staging.

**Pull request closed without merging**
