### PR TITLE
LPS-96155 getLayout changed to fetch

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/74073

**Pull request closed without merging**
