### PR TITLE
LPS-54544

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @arbetts

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Sent to Daniel for further review: https://github.com/danielkocsis/liferay-portal/pull/439

**Comment by danielkocsis** [comment]
ci: retest

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/25624. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
