### PR TITLE
LPS-50640

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@danielkocsis I've done some minor renaming and adjustments.  There's a few test gaps that we need:
(1) Need to test for scenarios where we have jobs in the queue.  The expected behavior is that queued jobs are never pulled up again for execution.  They should basically remain in the interrupted state.
(2) What happens in the lock scenario?  Let's say we cancelled a job that has acquired a lock, are we properly freeing up the lock?  I believe this is the case since the SerialBackgroundTaskExecutor should have picked it up.


@matethurzo fyi

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/danielkocsis/liferay-portal/pull/672. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/9c890479b449~3...9c890479b449) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/4576. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/6b234dbe139b~4...6b234dbe139b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
