### PR TITLE
LPS-91977 At this point just overwrite instead of deprecate

### PR DESCRIPTION
**Pull request by giros**

### CODE REVIEW

**Comment by giros** [comment]
ci:test:sf

**Comment by giros** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73319. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/85732333bb47~3...85732333bb47) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73320. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/5bf3c5cc66b7~4...5bf3c5cc66b7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73328. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/84bc8aa96364~4...84bc8aa96364) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73347. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/549bfdd20c37~4...549bfdd20c37) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
