### PR TITLE
LPS-70549

### PR DESCRIPTION
**Pull request by mbowerman**
Hey @danielkocsis,

Did you have a reason for removing the Ignore annotations from the tests that you copied over from EIHUT to BEICPT? Many of them seem to cause WARN messages to appear in the logs, causing the test suite to fail (see https://github.com/brianchandotcom/liferay-portal/pull/47008).

If you're good with these changes, please forward this to Brian Chan. Since the current behavior easily allows for Liferay to get stuck in an infinite loop, this seems fairly urgent to me.

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey guys, I need to check one use case, that looks suspicious to me.

I'm going to download the pr and check it.

Thanks!!

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Hey Guys,

@robertoDiaz thanks for checking this!

@mbowerman I removed the @Ignore annotations because these tests should run, it seems these were ignored because when we did a refactor a while ago, we did not have time to refactor the tests as well. So we definitely need to take care of these tests to make sure this complicated logic works well. I could see the warnings, so my plan was for today to fix those, but wanted to re-base and add missing cases first, that is why I sen you my pull originally.

If you guys agree that the logic looks like as it should, then I can finish the refactor of the tests.

thanks,
Daniel

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
@danielkocsis 

I've test it in a bunch of cases and it seems to work fine.

@mbowerman, thanks for the fix!!

👍

**Comment by robertoDiaz** [comment]
FYC

@matethurdo requested to add test in this [comment](https://github.com/brianchandotcom/liferay-portal/pull/46947#issuecomment-280645213) in the original pr

I think they have been covered by @mbowerman tests. 

If you find a missing case, please tell me and I could add this.

Thanks!!

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/mbowerman/liferay-portal/pull/31. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/f509596~4...f509596) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
