### PR TITLE
LPS-93303

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-93303

### CODE REVIEW

**Comment by giros** [comment]
ci:test:sf

**Comment by giros** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72922. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
