### PR TITLE
Lps 50640

### PR DESCRIPTION
**Pull request by shuyangzhou**
@danielkocsis let this pull finish, I have not ran the whole pr yet. There could be other failures. But the one that bothers you, should have been fixed by https://github.com/shuyangzhou/liferay-portal/commit/ba449f903b899fdba3c84ce636085388a648cc30

Sorry for the delay, I have been busy, finally got a moment today for this.

So the problem is not yours, it was created by https://github.com/shuyangzhou/liferay-portal/commit/ff216211637c8c3f82e652fb35357096f02ae14c . You were just unfortunately step on the long buried bomb.
I guess you must wonder why it is only started to show up after your change. It is because of this https://github.com/shuyangzhou/liferay-portal/commit/433f5ed62400efb8cea74984764b5c9d0d3a04e9#diff-40fc77287d9b94d6d6ac2e535aebaf10R349
You forced it to go through a new tx, and bypassing the finder/entity cache, therefore a real db fetch and hibernate deserialization must happen. Then the unintended Long to Inter convertion happened, caused the cast failure.
Before this change, the refetch will hit the cache, won't trigger a db fetch or hibernate deserialization, and we were just by luck to not see this failure. Because if for whatever reason the cache gets cleared or expired, a real refetch and deserialization will eventually happen, then it will fail in the exact same way.

Hope I explained the failure for you. Good luck with the rest of your changes :)

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Since this is a subrepo change, I am just going to send it out directly. It is a bug fix not really related to your stuff anyway.

**Comment by shuyangzhou** [comment]
See https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/322

**Comment by shuyangzhou** [comment]
I guess you guys would be interested in this too, @mhan810 @matethurzo

I merged in https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/322 already, and master syncing is in process https://github.com/liferay/liferay-portal/pull/1724 . Once the sync is done, we can rerun this pull  without the last commit (as it will be in master already) for a full pr test, hope nothing else breaks.

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/danielkocsis/liferay-portal/pull/677. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/989825f35e11~4...989825f35e11) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/4622. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/ddf9be0af730~4...ddf9be0af730) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
