### PR TITLE
LPS-90809 Description length is not validated at creating new change lists

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

During testing I noticed the card's footer is not clear fixed, My last commit solves that. However it reviled that the 2 cards does not have the same height.

I decided to create another ticket to solve that minor issue -> [LPS-95596](https://issues.liferay.com/browse/LPS-95596)

Please review my changes

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/1790. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/fdd75d406840~1...fdd75d406840) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
