### PR TITLE
[TS] LPS-98019

### PR DESCRIPTION
**Pull request by brianikim**
Hello @danielkocsis ,

Notes from @matthewchan123:

> https://issues.liferay.com/browse/LPS-98019
> 
> Issue:
> Keyword name of search bar cannot be modified from configurations once staging is enabled.
> 
> Cause:
> We swap the plids of themeDisplays passed into PortletPreferencesLocalServiceImpl.java for plids associated with LayoutRevisions. This was likely implemented due to inconsistencies of plid between themeDisplays of staged and live sites. Since we had added the _swapPlidForPortletPreferences() call to get, add, and update methods and forgot it in fetchPortletPreferences(), it creates the issue where either the wrong preferences or null is fetched.
> 
> Fix:
> Since we had passed in the plid for [themeDisplay](https://github.com/liferay/liferay-portal/blob/7.1.x/modules/apps/portal-search/portal-search-web/src/main/java/com/liferay/portal/search/web/internal/portlet/preferences/PortletPreferencesLookupImpl.java#L50) rather than LayoutRevision, we simply need to utilize _swapPlidForPortletPreferences() for fetching portletPreferences. Then, the correct database table row is fetched and the keyword name can be updated.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by renatakovacs** [comment]
Note: Dániel Kocsis and Tamás Molnár is on holiday. HU support WCM team checked the fix and we will create an sdh based on this change.

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/8010. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
