### PR TITLE
LPS-95172 edit journal related components publish/save label changed

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73154. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/8be1e4440dc9~2...8be1e4440dc9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
