### PR TITLE
Ftl templates for background task

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by danielkocsis** [comment]
Hey Andrew,

sorry, but did not have time today to check this, let me see it on Monday.

thanks,
Daniel

**Comment by danielkocsis** [comment]
Hey Andrew,

I held a background Task Friday today :) so finally I was able to check your solution. To be honest, I really love this new ftl template stuff. It is so much cleaner and more generic that the previous ones, and clean enough to say it is not over engineered. We do not have ugly JSON wrapper objects and stuff, so the direction is pretty good. 

I have noticed one thing though with the display object. Right now, as far as I understand, one display object represent the state of the execution in the moment of its creation time. So if I want to properly display the status of my task, let's say in every 2 seconds, I have to instantiate as many new objects as many times I refresh the UI. And during a few hours running task (which is not an extreme situation knowing the remote publishing performance :D) it can be a huge number of new objects, which ones are garbage collectible, but still. 

Could we somehow transform it to more of a translator model? What I am thinking about is something like the status message translator. So we could introduce a BTDisplayStatusTranslator, and still have a display object, probably registered like the statuses with a BTDisplayRegistry.register(new BTDisplay(bt)) in the BTMessageListener when starting a task. Or we could introduce a new extended BTStatus class, or a new additional interface the status could implement, like DisplayableBTS, that automatically calls the translator for the display methods. Or separate it a bit and still have a distinct BTDisplay object, but holds an instance of it in a BTStatus when creating a new status object, and get the Display from the BTStatus so we do not need a new registry and stuff for that.

The UI (the tag probably) should get the display from the registry and should call the methods like getPercentage() from the BTDisplay instance, but it would call the translator on the BTStatus instead of giving back its own state. I guess the BTStatus holds the state of the running task, so we shouldn't introduce new objects with state holds BT execution information.

So the whole data flow would be this:

BT execution -> BTSMessageSender ->(tranformation with BTSMT) -> BTStatus

BTStatus -> [??BTDisplay??] -> (transformation with BTDT)  -> UI (status tag)

What do you think?
Daniel

**Comment by danielkocsis** [comment]
I forgot that I'll be in a conference next week, so probably won't be able to check any pulls, but if you have questions/ideas feel free to reach me!

**Comment by arbetts** [comment]
@danielkocsis 

thanks for taking a look at this! i'm glad the FTL solution looks good.

I'm going to finalize some of these changes and send a pull that creates the multiple tags ( like we talked about before), but i was wondering if we can push the performance modifications till after we have this part committed?

we won't really know the performance concerns until we profile it with a large publish... and in general the garbage collector may not actually be an issue since this will only happen while the user is viewing the background task progress. if they navigate away from the page, then it will stop creating/displaying the progress and there is no garbage collector overhead.

I'd really like to be able to move forward with something, even if its with the intention of modifying it later. I have limited time to put toward story LPSs unless driven by a customer support ticket.

**Pull request closed without merging**
