### PR TITLE
[TECHNICAL-SUPPORT] LPS-69904

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @Alec-Shay

### CODE REVIEW

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Hey @jonathanmccann , @Alec-Shay,

Happy new year! :) 

I was able to check the pull, and please see my comments here:

- since your issue happens after an upgrade, because of a missing value, the proper fix for your case would be an upgrade script, that would add a last publish date preference for all the portlets where it is necessary (probably the last publish date of the site). I can't recall correctly what has changed exactly in the portlet last publish date logic between 6.0 and 6.2, 7.0 so please double check this option first.
- however I was able to reproduce the issue without needing to upgrade, only with local staging and a site portlet (I also updated the ticket desc. with my steps) so it seems the change is valid independently from the upgrade issue
- since all tests were passed before-after the fix, it seems we need a new test for this case, so please add test scenarios to ExportImportDateUtilTest to make sure we preserve this logic in the future

Please resend the pull with the tests and also please check the upgrade script options as well!

thanks,
Daniel

**Comment by Alec-Shay** [comment]
Hi @danielkocsis,

Thanks for the input. I'll definitely work on adding a test case for this and resend. Also thanks for pointing out the simpler steps for reproducing the issue without an upgrade, as it's much easier to test without importing data.

As for your suggestion for an upgrade script -- the only reason I hesitate to do this is because, without a last publish date there already, it's hard to tell whether that data actually existed before the last publish, so we could be publishing data a customer may not want to be published. Without the last publish date already existing I don't see any way we could really guarantee that we're not doing this.

We'd have no way of knowing, for instance, whether administrators never published DDL content before (they could have always kept the box unchecked), so if we just blindly added such a last publish date to everything, we could be automatically publishing something with the script that was never supposed to be published.

Is there a way you can think to get around this that would justify creating such a script? Or maybe it's not as bad as I expect it could be? I'm not opposed to creating a script potentially, I just don't want to mess up a customer's workflow or even cause a security issue because of an unintended publish.

**Comment by Alec-Shay** [comment]
Resent this change with a test at https://github.com/danielkocsis/liferay-portal/pull/592

**Pull request closed without merging**
