### PR TITLE
LPS-95586 history screen's error message won't show when other portlet is diplayed

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/rolandpakai/liferay-portal/pull/13. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
