### PR TITLE
LPS-66969 Java 8 compatbility

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Hey Máté,

It's great to see this done, thanks!

One question I have for you is, are we storing the exact bundle version? If so, is the check exact or does it allow for micro changes to consider the LAR still valid?

**Comment by matethurzo** [comment]
@JorgeFerrer the logic is the following: major has to be an exact match, older minor can be imported into newer and bugfix version basically doesn't matter.

so 2.0.3 into 3.0.6 :-1: 
3.0.5 into 3.0.9 :+1: 
3.6.2 into 3.8.2 :+1: 
but 3.8.2 into 3.6.2 :-1:

**Comment by JorgeFerrer** [comment]
That looks great. 

Is that just for the bundle-version or also for the individual schemaVersion per data handler?

If it's the latter, is it documented and communicated to all teams so that they follow those rules in the data handler's code?

**Comment by matethurzo** [comment]
@JorgeFerrer the data handlers are validated too individually based on the same logic.

the documentation is missing for that, and also good point to communicate to different teams. I'll notify everyone about it.

**Comment by JorgeFerrer** [comment]
Cool, thanks.

**Pull request closed without merging**
