### PR TITLE
LPS-73131 Make content processor tests less strict

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @danielkocsis,

I'm sending this to you, as you were having problems with this same
test the other day; also, I'm not sure about the `_assert*` method
names.

Everything passes when running the tests locally.

/cc @sergiogonzalez

Thanks

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
@sergiogonzalez @danielkocsis Any idea why this is failing? I don't see any startup error in the logs -- the only failure is the poshi test -- and locally everything seems ok. I have no clue about what's happening here :-(

**Comment by adolfopa** [comment]
ci:retest

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49760. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
