### PR TITLE
Lps 69227 NullPointerException when enabling local staging for a site that has no name in the instance's default language

### PR DESCRIPTION
**Pull request by tinatian**
Hi Daniel,

Could you please check if my change is OK to you?

The problem is we need to update group's name when default locale is changed, I think we'd better do the update in CompanyLocalServiceImpl instead of what you have done in user's modle listener. This way, it won't have performance affects for invocations on user.

Tina.

### CODE REVIEW

**Comment by danielkocsis** [comment]
Hey @tinatian,

if I am right (maybe not, so please feel free to correct me) it iterates through the same set of groups, that our solution did. I mean it uses the same query, it filters out the same results, and at the end it modifies the same groups. So the only thing it differs is the trigger what invokes to call this logic, right? Because Brian's concern, as far as I remember was that probably to update a 100 or 1000 or 10k groups would take so much time, what I don't know how could we make faster to be honest. Since this is the requirement of the business functionality.

thanks,
Daniel

**Comment by tinatian** [comment]
Hi @danielkocsis ,

You are right, the only I did is to move the logic from model listener to CompanyLocalService.

When I first saw your changes, the performance issue I think was that each time you invoke an update on any user, your logic will be invoked, which will affect every user. By moving the logic to CompanyLocalService, I think we can avoid this performance affect.

I did not notice there will be so many groups need to be updated, which you think is a performance issue. Yes, it might be a performance issue if you have like 10k or more groups.

Suppose some one do have that many groups, when you want to modify the default locale, it will take much more time to return, and client might see the UI is freezing. Like you said, this updating groups' name map is inevitable, if that's the case, the only thing we can do is to make client more comfortable with UI. I do not think we can move all the updating to background or in other thread to make current page return quickly, this update should be sync with default local's update, right?

Before we are trying to find a solution for this, I would like to ask "how many groups would a real word client have?" We only need to fix performance issue when it can really happen.


Tina.

**Comment by danielkocsis** [comment]
Hey @tinatian, 


I double checked Brian's concern (https://github.com/brianchandotcom/liferay-portal/pull/46124#issuecomment-272373324) and now I can see he mentioned the event it triggers this action. Since you changed this part, I would say then it should be OK now. 

However I am still worried about the process time for a huge amount of groups, but all the DB dump's I have seen contained 10k groups as a maximum. It happens when the Hopefully it won't cause a huge drop in performance, but I can still see it as a risky operation. 

Daniel

**Comment by tinatian** [comment]
Hi @danielkocsis,

10k groups you saw from clients' dump include user groups, right? If we can skip all the user's group, there won't be too many left.

According to the database created by default, I can see those user groups' "name" column is null, which means we do not need to update those groups. So I am wondering if we skip those kind of groups when retrieving from database, so that we can  iterate a much smaller size of results.

I am not familiar with the usages of user and groups, so please correct me if I made any mistake here.

Tina.

**Comment by danielkocsis** [comment]
Hey @tinatian,

unfortunately staging is also supported for user groups, so we can't skip them. As far as I can see either we can commit this fix in this form since we can't make it much faster and/or as you suggested we can start to think about how should we inform the user through the UI that this process can take longer time since it can work on a huge amount of data sometimes. So I am would also like to ask your opinion about do you think we should send this code to Brian as-is or I should start a conversation with the team responsible for the component what handles this business functionality and probably convert this bug to a story?

thanks,
Daniel

**Comment by tinatian** [comment]
If you ask my opinion, I would leave this potential performance issue when it really happens. 

Since this is one-time thing, I mean, it only takes a long time when you modify default language, it won't be that hard for clients to accept it may take a little longer than a normal action. But if we do see UI is frozen for a long time, we sure need to do something about it.

Tina.

**Comment by danielkocsis** [comment]
then I think this change is fine. Do you want me to send it to Brian or you would like to send it?

**Comment by tinatian** [comment]
Could you please send it to Brian? I did not fix the issue, the only thing I do is move it to another place, so if you agree with my moving, could you please redo it? Also I did not add your dynamic query changes, I am not sure if you still want it.

Thanks.
Tina.

**Pull request closed without merging**
