### PR TITLE
LPS-92470 buildLang

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74017. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/2bcec642094a~4...2bcec642094a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74060. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/cb1935eddda7~5...cb1935eddda7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
