### PR TITLE
[TECHNICAL-SUPPORT] LPS-70386

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Hey @jonathanmccann,

the same applies to this one as to https://github.com/danielkocsis/liferay-portal/pull/598. Please see JournalArticleExportImportContentProcessorTest to get some examples how to develop a test like this.

thanks,
Daniel

**Comment by mbowerman** [comment]
Hi @danielkocsis,

Please see https://github.com/danielkocsis/liferay-portal/pull/601.

**Pull request closed without merging**
