### PR TITLE
LPS-72834

### PR DESCRIPTION
**Pull request by JoshuaStClair**
/cc @kmaria

Hi guys, 
As per PR https://github.com/danielkocsis/liferay-portal/pull/660, I fixed the NPE so you can continue your testing.

### CODE REVIEW

**Comment by JoshuaStClair** [comment]
ci:retest

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/kmaria/liferay-portal/pull/30. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49982. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
