### PR TITLE
[TECHNICAL-SUPPORT] LPS-97544 Default classPK refers to the wrong JournalArticle

### PR DESCRIPTION
**Pull request by vendeltoreki**
[LPS-97544](https://issues.liferay.com/browse/LPS-97544)

Hi @danielkocsis ,

As discussed, I'm re-sending https://github.com/danielkocsis/liferay-portal/pull/837 with the following modification:
Add a method to `PortletDataContext` to get the mapped key values directly, and use this method in `JournalArticleExportImportContentProcessor`.

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75514. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75700. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
