### PR TITLE
LPS-60027 DestinationFactory might not be always present

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
hey @danielkocsis, 

I sent the pull to Brian but it can't be merged because of rebase conflicts. Brian says there are errors with some Rules 😖 .

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/danielkocsis/liferay-portal/pull/543. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/danielkocsis/liferay-portal/pull/544. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/85c9390~4...85c9390) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39027. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/a932373~4...a932373) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/csierra/liferay-portal/pull/235. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/61c8525~4...61c8525) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
