### PR TITLE
LPS-98264 org.junit.ComparisonFailure in LayoutSetPrototypePropagationTest

### PR DESCRIPTION
**Pull request by topolik**
https://issues.liferay.com/browse/LPS-98264

### CODE REVIEW

**Comment by topolik** [comment]
ci:test:sf

**Comment by topolik** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
ci:test:staging

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75767. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/14dc6053db2d~1...14dc6053db2d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
