### PR TITLE
LPS-91573 breadcrumbs added to history details screen

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zoltancsaszi** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74023. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/63d9dd5980dd~2...63d9dd5980dd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74070. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/d925e009cf12~2...d925e009cf12) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
