### PR TITLE
LPS-95505 structure and template only tracked if change tracking supported for referred class

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:change-tracking

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73162. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/0f098098a8c5~1...0f098098a8c5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
