### PR TITLE
LPS-95597

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-95597

### CODE REVIEW

**Comment by giros** [comment]
ci:test:sf

**Comment by giros** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73302. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/6914f297b505~3...6914f297b505) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73303. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/719a010eff59~3...719a010eff59) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73346. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/8061aca71b04~3...8061aca71b04) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
