### PR TITLE
LPS-97755 affected entry resource integration tests added

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:change-tracking

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76346. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/6f3ccde7576d~1...6f3ccde7576d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
