### PR TITLE
LPS-96316 getCTEntryOptional returns the given versionEntity's ctEntry from any change list

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74220. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/5a836c62a022~1...5a836c62a022) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
