### PR TITLE
[TECHNICAL-SUPPORT] LPS-71050

### PR DESCRIPTION
**Pull request by matethurzo**
/cc @Alec-Shay

### CODE REVIEW

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48188. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/3ddc684cf635~2...3ddc684cf635) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Alec-Shay** [comment]
Thanks!

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48205. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/94e55b34bc82~2...94e55b34bc82) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
