### PR TITLE
LPS-93301

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-93301

New gray color is $gray-500 from https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/bootstrap/_variables.scss#L13-L21

### CODE REVIEW

**Comment by giros** [comment]
ci:test:sf

**Comment by giros** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72923. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
