### PR TITLE
LPS-91972 publishing change list also checks out production, scheduled publication is disables

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72765. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/4427e233d729~1...4427e233d729) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
