### PR TITLE
LPS-68539

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:reopen

**Comment by danielkocsis** [comment]
ci:retest

**Comment by danielkocsis** [comment]
ci:retest

**Comment by danielkocsis** [comment]
ci:retest

**Comment by danielkocsis** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest (to generate the bundles)

**Comment by pyoo47** [comment]
I've uploaded the bundles here: https://test-1-0.liferay.com/userContent/tmp/

Please let me know when you're done with them so I can remove them.

**Pull request closed without merging**
