### PR TITLE
[TECHNICAL-SUPPORT] LPS-73061

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Hey @jonathanmccann,

please add the fix to `BaseTextExportImportContentProcessor`, however it is deprecated we would like to maintain it for now because a few components still uses it. And also please add a test case to the `DefaultExportImportContentProcessorTest` (it means just add a few lines to the `layout_links.txt` with following the pattern).

**Comment by mbowerman** [comment]
Hi @danielkocsis,

Please see https://github.com/danielkocsis/liferay-portal/pull/656.

**Pull request closed without merging**
