### PR TITLE
LPS-95792 if user setting is true, a confirmation is displayed before checking out change lists

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zoltancsaszi** [comment]
ci:test:change-tracking

**Comment by zoltancsaszi** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73465. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
