### PR TITLE
LPS-94539 changing change list on overview screen refreshes indicator tooltip

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/NemethNorbert/liferay-portal/pull/13. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/0a7acde4a916~1...0a7acde4a916) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73247. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/0a7acde4a916~1...0a7acde4a916) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
