### PR TITLE
LPS-92314

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-92314

### CODE REVIEW

**Comment by giros** [comment]
ci:test:sf

**Comment by giros** [comment]
ci:test:change-tracking

**Comment by giros** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74572. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/318f9743795e~1...318f9743795e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
