### PR TITLE
[TECHNICAL-SUPPORT] LPS-97025 Delete and re-add page in site template

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @danielkocsis ,

You can find details in my [jira comment](https://issues.liferay.com/browse/LPS-97025?focusedCommentId=1869405&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1869405).
Since I'm changing PortalImpl, this might need a core review as well.

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Hi @vendeltoreki,

please find mi in person to discuss it further!

thanks,
Daniel

**Comment by vendeltoreki** [comment]
Closing this as new PR opened: https://github.com/danielkocsis/liferay-portal/pull/832

**Pull request closed without merging**
