### PR TITLE
LPS-91977

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-91977

### CODE REVIEW

**Comment by giros** [comment]
ci:test:sf

**Comment by giros** [comment]
ci:test:change-tracking

**Comment by giros** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/danielkocsis/liferay-portal/pull/747. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/7f6237715129~5...7f6237715129) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/giros/liferay-portal/pull/107. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/d25921b9e871~6...d25921b9e871) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
