### PR TITLE
LPS-72207 - Cannot link the URL of Web Content management page to a Web Content.

### PR DESCRIPTION
**Pull request by matethurzo**
@matethurzo  discussed with our team, as the issue is an EE customer, according to my test, the web content export and import functions do not work as expected,  I hope you can continue to review it.

### CODE REVIEW

**Comment by danielkocsis** [comment]
Hey @daviddotzhang,

could you please add this scenario to the `DefaultExportImportContentProcessorTest` as well? Without a test, since this processor is already really complex, we can't accept any changes to the logic.

You can re-send the pull to me once it is ready!

thanks,
Daniel

**Comment by daviddotzhang** [comment]
@danielkocsis   as I am not so familiar with the whole function.  could you create the tests for me?

By the way, currently, the web content export and import functions do not work.  you can test with the following link. the behavior changed as DXP brings in site admin URL  "/~/"

http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_auth=KFz6mGlg

**Comment by daviddotzhang** [comment]
ci: reopen

**Comment by danielkocsis** [comment]
@daviddotzhang I can give you a guideline of course, but please try to do it because our resources are very limited as well. 

So it is fairly easy, everything has already been prepared you just need to add your specific URL pattern to the  `layout_references.txt` or `invalid_layout_references.txt` in the export-import-test bundle. You can find many examples there, and all of these are validated by the test we already have.

**Pull request closed without merging**
