### PR TITLE
LPS-54744

### PR DESCRIPTION
**Pull request by arbetts**
@danielkocsis @matethurzo 

here are my final changes for adding the BackgroundTaskDisplay.

the one other thing i want to do is to move the polling logic out of expor-import/main.js and into the taglib  background-task-status end.jsp. That should just involve JS changes so i want to do that in a different LPS.

hopefully we can get this through and committed so i can finish up the story ticket before release! :)

### CODE REVIEW

**Comment by danielkocsis** [comment]
Hey @arbetts,

so I am back to work now and I have checked the pull. Other then the number of display objects (we can change it later). My only question is, do you think we can separate these changes into 2-3 smaller parts? I am afraid that Brian won't review it if it has this size in changes, so it would makes sense to have a display object - tag separation. Is it possible to do this?

**Comment by arbetts** [comment]
@danielkocsis 

we can try to break it up and do three LPSs, but the first two would be broken until the third is committed.

(we'd have to rename LPS-59712, and LPS-55934)
LPS-54744 = fe9e1db -> 1b9ade6
LPS-59712 = a2c10db -> 78429ed
LPS-55934 = cf10313 -> 870bad8

I couldn't find a way to truly separate these parts without leaving staging in a broken state... if that's acceptable then we can do this.

**Comment by danielkocsis** [comment]
Since we are working on staging UI's currently i think this is acceptable

**Comment by arbetts** [comment]
@danielkocsis 

ok, i'll break it up and send them to you

**Comment by arbetts** [comment]
i've rebased this one and removed the extra commits ... this won't allow master to compile without the next LPS, but it does split up the changes

**Comment by danielkocsis** [comment]
https://github.com/arbetts/liferay-portal/pull/32

**Pull request closed without merging**
