### PR TITLE
[TS] LPS-91959

### PR DESCRIPTION
**Pull request by balazssk**
Hi @danielkocsis 

The aim of this fix is to create a way to control the publication of page deletions if the checkbox <Replicate Individual Deletions> is checked. Currently only Content types had their own checkbox, this fix introduces the Publish Page Deletions checkbox.

A little difference from the mockup https://issues.liferay.com/secure/attachment/312037/LPP-33064.png is that the deleted pages don't have their own tree to visalise which page's deletion is to be published. This would have needed a major change in how SystemEvents store page deletions. It might be raised as a separate feature request later.

Can you please review?
https://issues.liferay.com/browse/LPS-91959

Thanks,

### CODE REVIEW

**Comment by balazssk** [comment]
Force pushed as there was a language properties conflict

**Comment by danielkocsis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/danielkocsis/liferay-portal/pull/816. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/fd0185f2da90~1...fd0185f2da90) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/kmaria/liferay-portal/pull/140. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/2acfa0d69049~2...2acfa0d69049) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74523. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/2acfa0d69049~2...2acfa0d69049) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
Pull request submitted to https://github.com/balazssk/liferay-portal/pull/10. [See changes here.](https://github.com/danielkocsis/liferay-portal/compare/2acfa0d69049~2...2acfa0d69049) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
