### PR TITLE
LPS-65811 use the same article id used to create the new version later

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @jorgediaz_lr

**Comment by jorgediaz-lr** [comment]
@juliocamarero my user is @jorgediaz-lr  :stuck_out_tongue:

**Comment by anthony-chu** [comment]
@juliocamarero @jorgediaz-lr @danielkocsis

I've tested this fix in conjunction with the fix in brianchandotcom#40066. After cherry-picking the fixes from there, no DuplicateArticleIdException or NoSuchStorageLinkException is thrown during the staging process, and articles are published successfully.

**Comment by juliocamarero** [comment]
Awesome! Thanks a lot @anthony-chu! :)

**Comment by danielkocsis** [comment]
Hi Guys,

I have started to check this yesterday, and it works for the given reproductions steps, however after I wrote a test to preserve this behavior I found it also has another issue, so I haven't sent it yet, because I want to fix that issue first. 

thanks,
Daniel

**Comment by danielkocsis** [comment]
Pull request submitted to github.combrianchandotcom/liferay-portal/pull/40119. [See changes here.](github.comdanielkocsis/liferay-portal/compare/0c1616a~2...0c1616a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
