### PR TITLE
LPS-55934

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
@danielkocsis 

would you be able to take a look at this? the other dependent LPSs are committed now so we can create the background task status tag.

I wan't 100% sure on the actual display you wanted in the staging UI, so I think you can change it to display what you need?

also, i tried testing this by staging and i got a lot of staging related errors. I don't think the errors are coming from the UI, but I can resend if you find something broken.

**Comment by arbetts** [comment]
ci:retest

**Comment by danielkocsis** [comment]
Hey Andrew,


I have seen the changes on the master, looks pretty good! I am not sure I can spend any time on that today, but I'll try, if not I promise I'll check it on Monday.

Daniel

**Comment by danielkocsis** [comment]
Hey Andrew,


I was able to check the pull, and have the following questions/comments (I am not a UI expert though, so maybe stupid ones): 

1. Could you apply the same changes to the Staging Processes Web portlet?
2. Is it intended to use the same init.jsp for all the tags? Do the other hierarchical ones, like search container uses the same approach? If now, could you refactor to those to have separated init's and parameters. It would be also beneficial, because in this way everyone could use these tags independently, if they want to, but also would be able to combine those.
3. What is the BackgroundTaskSatusRequiredTag class good for? I've tried to find similar classes, but haven't found. Could you detail me this?

thanks,
Daniel

**Comment by danielkocsis** [comment]
ci:retest

**Comment by arbetts** [comment]
@danielkocsis 
1) Could you apply the same changes to the Staging Processes Web portlet?
	yes, i can apply the changes there too. I think that module is fairly new so i missed it when refactoring.

2) Is it intended to use the same init.jsp for all the tags? Do the other hierarchical ones, like search container uses the same approach? If now, could you refactor to those to have separated init's and parameters. It would be also beneficial, because in this way everyone could use these tags independently, if they want to, but also would be able to combine those.
	i don't really know the pattern to use for the taglib changes. If we separate the tags then they would all have to pass in a backgroundTaskId and we would be duplicating some logic. That might be better since it gives more flexibility. I made them nested because that's what the logic was doing before.

What is the BackgroundTaskSatusRequiredTag class good for? I've tried to find similar classes, but haven't found. Could you detail me this?
	the class enforces the heirarchy. it just adds the requirement that a BackgroundStatusTag happens before the current tag. If the tags should not be nested then we can remove this class

**Comment by danielkocsis** [comment]
I think it would be better to separate tags, as you said, it gives more flexibility, and also don't need this require tag class. Of course the status tag still should be able to have  a body, to allow the dev's some customization on the UI. Could you do these changes and resend the pull?

**Comment by arbetts** [comment]
i'll separate them and then resend.

**Pull request closed without merging**
